### ISSUE TITLE
Error for call_service at pos 1: Unable to set value 35-37-0-targetValue

### ISSUE THREAD

**Issue by P-Verbrugge** [zwave-js/zwave-js-ui#4210]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Home Assistant Add-on

### Z-Wave JS UI version

4.1.1

### ZwaveJS version

15.1.0 / 3.0.0

### Describe the bug

bedroom_power_plug_television_turn_off: Error executing script. Error for call_service at pos 1: Unable to set value 35-37-0-targetValue: unknown_error: TypeError: (0 , import_serial.isAnySendDataResponse) is not a function at Driver.executeTransaction (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:6385:8) at processTicksAndRejections (node:internal/process/task_queues:105:5) at Driver.drainTransactionQueue (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:6270:5)

### To Reproduce

Create an automation that executes a script. In the script call the turn off function of a Fibaro power plug;

### Expected behavior

Expected the plug to turn off.

**Comment by dcmeglio** [comment]
I am having the same issue running this command:
```
action: zwave_js.multicast_set_value
data:
  device_id:
    - 47a51fb1c5eefe6acbda20d1430ecbb0
    - 6db2e43b0dc4aebd47c85838db4bd09c
    - dc32aa0c77f8996bf3a5693c336ece5c
    - b7e51fbfca1a052721858e5791bf4b87
    - 0462015716f9e0bf1ab11a448cb784ae
    - d054251a056b630925cbfadc7735f032
  command_class: "37"
  property: targetValue
  value: false
continue_on_error: true
```

I downgraded to 4.1.0 and it works fine.

**Comment by robertsLando** [comment]
@AlCalzone has this been fixed in latest driver version?

**Comment by AlCalzone** [comment]
Yes. There hasn't been an addon release yet though.

**Comment by robertsLando** [comment]
@P-Verbrugge @dcmeglio could you update please? Feel free to re-open this In case the issue persists

**Comment by wimjanse** [comment]
@robertsLando @P-Verbrugge with 4.1.2, still having issue with messages “transmission queue full”

**Comment by robertsLando** [comment]
@wimjanse PLease tell me Z-UI version as I have no clue about the mapping between zui and addon version...

**Comment by wimjanse** [comment]
See open issue #4217  Z-WaveUI version is 4.1.2 (z-wavejs version is 15.1.3/3.0.0)
